version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: stephen
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: open_heavens_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://stephen:qwerty@db:5432/open_heavens_db
      API_KEY: supersecret
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    ports:
      - "8000:8000"
volumes:
  db_data:
